# Generated by Django 4.1.1 on 2022-10-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('walletAddress', models.CharField(max_length=200)),
                ('cryptedPrivKey', models.CharField(max_length=500)),
                ('signaturePrivKey', models.BinaryField(editable=True, max_length=10000000)),
                ('emailAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('varifiedEmail', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('urlAddress', models.CharField(max_length=500)),
                ('upVote', models.IntegerField(default=0)),
                ('downVote', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
