# Generated by Django 4.1.1 on 2022-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signaturePrivKey',
            field=models.BinaryField(editable=True, max_length=1000),
        ),
    ]
