# Generated by Django 4.1.1 on 2022-10-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_signatureprivkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voteVal', models.CharField(max_length=50)),
                ('metaComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metacomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
