# Generated by Django 4.1.1 on 2022-10-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voteVal', models.CharField(max_length=50)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
