# Generated by Django 4.1.1 on 2022-11-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contentvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentVote',
            new_name='VoteOnContent',
        ),
    ]
