# Generated by Django 4.1.1 on 2022-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_nft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='ipfs',
            new_name='imgIpfs',
        ),
        migrations.AddField(
            model_name='nft',
            name='metaIpfs',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
