# Generated by Django 4.1.1 on 2022-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_vote_created_vote_towhom_voteoncontent_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isMinted',
            field=models.BooleanField(default=False),
        ),
    ]
